### ISSUE TITLE
Cannot create wixapp

### ISSUE THREAD

**Issue by ogeorg** [wix/generator-angular-wixapp#3]
I am trying to create a now wix app, but I cannot

I have installed nodejs on my ubuntu 14.04 box, npm and other modules requiered:

$ sudo npm install -g npm
$ sudo npm install -g bower
$ sudo npm install -g grunt-cli
$ sudo npm install -g yo

I had problems installing gnerator-angular-wixapp, so I found I had to do

$ sudo chown -R `whoami` ~/.npm
$ sudo chown -R `whoami` /usr/local/lib/node_modules
$ sudo npm install -g generator-angular-wixapp

and finally:
$ mkdir hello-world-wixapp
$ cd hello-world-wixapp
$ yo angular-wixapp

And got the following result:

------------------------------------------------------------------------------------
olivier@HPCompaq:~/Projects/hello-world-wixapp$ yo angular-wixappWelcome to Wix.com App Market application generator!

Note: In order to use Sass you have to install compass: http://compass-style.org/install/

? Would you like to use Sass?  No
   create Gruntfile.js
   create package.json
   create bower.json
   create .jshintrc
   create test/.jshintrc
   create .gitattributes
   create .gitignore
   create .bowerrc
   create app/robots.txt
   create app/styles/settings.css
   create app/styles/app.css
   create app/scripts/app.js
   create app/scripts/settings.js
   create app/scripts/controllers/settings.js
   create app/scripts/controllers/main.js
   create app/scripts/services/wix.js
   create app/views/app.html
   create app/views/settings.html
   create app/index.html
   create app/settings.html
   create app/translations/settings_en.json
   create app/images/wix_icon.png
   create test/karma.conf.js
   create test/spec/controllers/main.js

I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.

bower cached        git://github.com/angular/bower-angular-route.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular-route.git#~1.2.0
bower cached        git://github.com/jquery/jquery.git#1.9.1
bower validate      1.9.1 against git://github.com/jquery/jquery.git#~1.9.1
bower cached        git://github.com/wix/wix-ui-lib-bower.git#2.1.11
bower validate      2.1.11 against git://github.com/wix/wix-ui-lib-bower.git#~2.1.9
bower cached        git://github.com/PascalPrecht/bower-angular-translate.git#2.3.0
bower validate      2.3.0 against git://github.com/PascalPrecht/bower-angular-translate.git#~2.3.0
bower cached        git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.3.0
bower validate      2.3.0 against git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.3.0
bower cached        git://github.com/angular/bower-angular-mocks.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular-mocks.git#~1.2.0
bower cached        git://github.com/angular/bower-angular-scenario.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular-scenario.git#~1.2.0
bower cached        git://github.com/angular/bower-angular.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular.git#~1.2.0
bower extra-resolution      Unnecessary resolution: angular#~1.2.0
bower install               angular-translate-loader-static-files#2.3.0
bower install               angular-translate#2.3.0
bower install               wix-ui-lib2#2.1.11
bower install               angular-route#1.2.28
bower install               jquery#1.9.1
bower install               angular#1.2.28
bower install               angular-mocks#1.2.28
bower install               angular-scenario#1.2.28

angular-translate-loader-static-files#2.3.0 app/bower_components/angular-translate-loader-static-files
└── angular-translate#2.3.0

angular-translate#2.3.0 app/bower_components/angular-translate

wix-ui-lib2#2.1.11 app/bower_components/wix-ui-lib2

angular-route#1.2.28 app/bower_components/angular-route
└── angular#1.2.28

jquery#1.9.1 app/bower_components/jquery

angular#1.2.28 app/bower_components/angular

angular-mocks#1.2.28 app/bower_components/angular-mocks
└── angular#1.2.28

angular-scenario#1.2.28 app/bower_components/angular-scenario
└── angular#1.2.28
npm WARN package.json hello-world-wixapp@0.1.0 No description
npm WARN package.json hello-world-wixapp@0.1.0 No repository field.
npm WARN package.json hello-world-wixapp@0.1.0 No README data
npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead
npm WARN engine karma@0.10.10: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","npm":"2.5.0"})
npm WARN deprecated ngmin@0.4.1: use ng-annotate instead
 
> grunt-autoprefixer@0.5.0 postinstall /home/olivier/Projects/hello-world-wixapp/node_modules/grunt-autoprefixer
> 

 
> phantomjs@1.9.15 install /home/olivier/Projects/hello-world-wixapp/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-i686.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-i686.tar.bz2
Receiving...
/
Error making request.
Error: socket hang up
    at createHangUpError (_http_client.js:215:15)
    at TLSSocket.socketOnEnd (_http_client.js:293:23)
    at TLSSocket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Please report this full log at https://github.com/Medium/phantomjs
npm WARN engine coffee-script-redux@2.0.0-beta4: wanted: {"node":"0.6.x || 0.8.x"} (current: {"node":"0.12.0","npm":"2.5.0"})
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git Cloning into bare repository '/home/olivier/.npm/_git-remotes/git-github-com-michaelficarra-cscodegen-git-c4b567f3'...
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git fatal: read error: Connection reset by peer
npm WARN optional dep failed, continuing cscodegen@git://github.com/michaelficarra/cscodegen.git#73fd7202ac086c26f18c9d56f025b18b3c6f5383
npm ERR! fetch failed https://registry.npmjs.org/lodash/-/lodash-1.1.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ECONNRESET
npm ERR! fetch failed https://registry.npmjs.org/nopt/-/nopt-2.1.2.tgz
npm WARN retry will retry, error on last attempt: Error: connect ECONNRESET
npm WARN optional dep failed, continuing esmangle@~0.0.8
npm ERR! fetch failed https://registry.npmjs.org/socket.io/-/socket.io-0.9.17.tgz
npm WARN retry will retry, error on last attempt: Error: read ECONNRESET
npm ERR! fetch failed https://registry.npmjs.org/di/-/di-0.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: read ECONNRESET
npm ERR! fetch failed https://registry.npmjs.org/log4js/-/log4js-0.6.22.tgz
npm WARN retry will retry, error on last attempt: Error: read ECONNRESET
npm ERR! fetch failed https://registry.npmjs.org/fileset/-/fileset-0.1.5.tgz
npm WARN retry will retry, error on last attempt: Error: connect ECONNRESET
npm ERR! fetch failed https://registry.npmjs.org/resolve/-/resolve-0.5.1.tgz
npm WARN retry will retry, error on last attempt: Error: connect ECONNRESET
npm WARN optional dep failed, continuing fsevents@0.2.1
 [[B\
> ws@0.4.32 install /home/olivier/Projects/hello-world-wixapp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/olivier/Projects/hello-world-wixapp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/olivier/Projects/hello-world-wixapp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.0
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs@1.9.15 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/olivier/Projects/hello-world-wixapp/npm-debug.log
------------------------------------------------------------------------------------

Am I doing something wrong (first day using node.js)?
How can I solve this.

Thanks

Olviier Georg

**Comment by tautvilas** [comment]
Hi, it looks like that there were some network connection issues. Can you try running the generator again and see if the problem is still appearing?

**Comment by ogeorg** [comment]
Thanks for your answer.
I am doing this at home, so I'll try it again tonight (10 am here in Spain)
Olivier Georg

**Comment by ogeorg** [comment]
Hi tautvilas,

Ok, so I tried to run the generator again, and again I've got problems...

olivier@HPCompaq:~/Projects/hello-world-wixapp$ yo angular-wixapp
Welcome to Wix.com App Market application generator!

Note: In order to use Sass you have to install compass: http://compass-style.org/install/

? Would you like to use Sass?  No
   create Gruntfile.js
   create package.json
   create bower.json
   create .jshintrc
   create test/.jshintrc
   create .gitattributes
   create .gitignore
   create .bowerrc
   create app/robots.txt
   create app/styles/settings.css
   create app/styles/app.css
   create app/scripts/app.js
   create app/scripts/settings.js
   create app/scripts/controllers/settings.js
   create app/scripts/controllers/main.js
   create app/scripts/services/wix.js
   create app/views/app.html
   create app/views/settings.html
   create app/index.html
   create app/settings.html
   create app/translations/settings_en.json
   create app/images/wix_icon.png
   create test/karma.conf.js
   create test/spec/controllers/main.js


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


bower cached        git://github.com/angular/bower-angular.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular.git#~1.2.0
bower cached        git://github.com/angular/bower-angular-route.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular-route.git#~1.2.0
bower cached        git://github.com/jquery/jquery.git#1.9.1
bower validate      1.9.1 against git://github.com/jquery/jquery.git#~1.9.1
bower cached        git://github.com/wix/wix-ui-lib-bower.git#2.1.11
bower validate      2.1.11 against git://github.com/wix/wix-ui-lib-bower.git#~2.1.9
bower cached        git://github.com/PascalPrecht/bower-angular-translate.git#2.3.0
bower validate      2.3.0 against git://github.com/PascalPrecht/bower-angular-translate.git#~2.3.0
bower cached        git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.3.0
bower validate      2.3.0 against git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.3.0
bower cached        git://github.com/angular/bower-angular-scenario.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular-scenario.git#~1.2.0
bower cached        git://github.com/angular/bower-angular-mocks.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular-mocks.git#~1.2.0
bower extra-resolution      Unnecessary resolution: angular#~1.2.0
bower install               wix-ui-lib2#2.1.11
bower install               angular-translate#2.3.0
bower install               angular-translate-loader-static-files#2.3.0
bower install               jquery#1.9.1
bower install               angular-route#1.2.28
bower install               angular-mocks#1.2.28
bower install               angular-scenario#1.2.28
bower install               angular#1.2.28

wix-ui-lib2#2.1.11 app/bower_components/wix-ui-lib2

angular-translate#2.3.0 app/bower_components/angular-translate

angular-translate-loader-static-files#2.3.0 app/bower_components/angular-translate-loader-static-files
└── angular-translate#2.3.0

jquery#1.9.1 app/bower_components/jquery

angular-route#1.2.28 app/bower_components/angular-route
└── angular#1.2.28

angular-mocks#1.2.28 app/bower_components/angular-mocks
└── angular#1.2.28

angular-scenario#1.2.28 app/bower_components/angular-scenario
└── angular#1.2.28

angular#1.2.28 app/bower_components/angular
npm WARN package.json hello-world-wixapp@0.1.0 No description
npm WARN package.json hello-world-wixapp@0.1.0 No repository field.
npm WARN package.json hello-world-wixapp@0.1.0 No README data
npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead
npm WARN engine karma@0.10.10: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","npm":"2.5.0"})
npm WARN deprecated ngmin@0.4.1: use ng-annotate instead
 
> grunt-autoprefixer@0.5.0 postinstall /home/olivier/Projects/hello-world-wixapp/node_modules/grunt-autoprefixer
> 

 
> phantomjs@1.9.15 install /home/olivier/Projects/hello-world-wixapp/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Downloading https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-i686.tar.bz2
Saving to /tmp/phantomjs/phantomjs-1.9.8-linux-i686.tar.bz2
Receiving...
/ [=====================================---] 92% 0.0s/
Received 13200K total.
Extracting tar contents (via spawned process)
Removing /home/olivier/Projects/hello-world-wixapp/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-i686.tar.bz2-extract-1423691521778/phantomjs-1.9.8-linux-i686 -> /home/olivier/Projects/hello-world-wixapp/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/olivier/Projects/hello-world-wixapp/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm WARN optional dep failed, continuing fsevents@0.2.1
npm WARN engine coffee-script-redux@2.0.0-beta4: wanted: {"node":"0.6.x || 0.8.x"} (current: {"node":"0.12.0","npm":"2.5.0"})
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git Cloning into bare repository '/home/olivier/.npm/_git-remotes/git-github-com-michaelficarra-cscodegen-git-c4b567f3'...
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git github.com[0: 192.30.252.130]: errno=Connection reset by peer
npm WARN optional dep failed, continuing cscodegen@git://github.com/michaelficarra/cscodegen.git#73fd7202ac086c26f18c9d56f025b18b3c6f5383
npm WARN optional dep failed, continuing esmangle@~0.0.8
 
> ws@0.4.32 install /home/olivier/Projects/hello-world-wixapp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/olivier/Projects/hello-world-wixapp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/olivier/Projects/hello-world-wixapp/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
npm ERR! Linux 3.13.0-45-generic
npm ERR! argv "node" "/usr/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.0
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read

npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/olivier/Projects/hello-world-wixapp/npm-debug.log

**Comment by ogeorg** [comment]
OK, I've just done it again, and now it seems to install correctly. Also runs correctly.
Thanks...

BTW on entering back into the computer, I had to set the env. var 
<code>export NODE_PATH=/usr/local/lib/node_modules/</code>

It would be useful to mention it in the tutorial

<pre>
olivier@HPCompaq:~/Projects/hwwa$ yo angular-wixapp
Welcome to Wix.com App Market application generator!

Note: In order to use Sass you have to install compass: http://compass-style.org/install/

? Would you like to use Sass?  No
   create Gruntfile.js
   create package.json
   create bower.json
   create .jshintrc
   create test/.jshintrc
   create .gitattributes
   create .gitignore
   create .bowerrc
   create app/robots.txt
   create app/styles/settings.css
   create app/styles/app.css
   create app/scripts/app.js
   create app/scripts/settings.js
   create app/scripts/controllers/settings.js
   create app/scripts/controllers/main.js
   create app/scripts/services/wix.js
   create app/views/app.html
   create app/views/settings.html
   create app/index.html
   create app/settings.html
   create app/translations/settings_en.json
   create app/images/wix_icon.png
   create test/karma.conf.js
   create test/spec/controllers/main.js


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


bower cached        git://github.com/angular/bower-angular.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular.git#~1.2.0
bower cached        git://github.com/angular/bower-angular-route.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular-route.git#~1.2.0
bower cached        git://github.com/jquery/jquery.git#1.9.1
bower validate      1.9.1 against git://github.com/jquery/jquery.git#~1.9.1
bower cached        git://github.com/PascalPrecht/bower-angular-translate.git#2.3.0
bower validate      2.3.0 against git://github.com/PascalPrecht/bower-angular-translate.git#~2.3.0
bower cached        git://github.com/wix/wix-ui-lib-bower.git#2.1.11
bower validate      2.1.11 against git://github.com/wix/wix-ui-lib-bower.git#~2.1.9
bower cached        git://github.com/angular/bower-angular-mocks.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular-mocks.git#~1.2.0
bower cached        git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.3.0
bower validate      2.3.0 against git://github.com/PascalPrecht/bower-angular-translate-loader-static-files.git#2.3.0
bower cached        git://github.com/angular/bower-angular-scenario.git#1.2.28
bower validate      1.2.28 against git://github.com/angular/bower-angular-scenario.git#~1.2.0
bower extra-resolution      Unnecessary resolution: angular#~1.2.0
bower install               wix-ui-lib2#2.1.11
bower install               angular-translate#2.3.0
bower install               angular#1.2.28
bower install               jquery#1.9.1
bower install               angular-translate-loader-static-files#2.3.0
bower install               angular-scenario#1.2.28
bower install               angular-route#1.2.28
bower install               angular-mocks#1.2.28

wix-ui-lib2#2.1.11 app/bower_components/wix-ui-lib2

angular-translate#2.3.0 app/bower_components/angular-translate

angular#1.2.28 app/bower_components/angular

jquery#1.9.1 app/bower_components/jquery

angular-translate-loader-static-files#2.3.0 app/bower_components/angular-translate-loader-static-files
└── angular-translate#2.3.0

angular-scenario#1.2.28 app/bower_components/angular-scenario
└── angular#1.2.28

angular-route#1.2.28 app/bower_components/angular-route
└── angular#1.2.28

angular-mocks#1.2.28 app/bower_components/angular-mocks
└── angular#1.2.28
npm WARN package.json hwwa@0.1.0 No description
npm WARN package.json hwwa@0.1.0 No repository field.
npm WARN package.json hwwa@0.1.0 No README data
npm WARN deprecated grunt-ngmin@0.0.3: use grunt-ng-annotate instead
npm WARN engine karma@0.10.10: wanted: {"node":"~0.8 || ~0.10"} (current: {"node":"0.12.0","npm":"2.5.0"})
npm WARN deprecated ngmin@0.4.1: use ng-annotate instead
 
> grunt-autoprefixer@0.5.0 postinstall /home/olivier/Projects/hwwa/node_modules/grunt-autoprefixer
> 

 
> phantomjs@1.9.15 install /home/olivier/Projects/hwwa/node_modules/karma-phantomjs-launcher/node_modules/phantomjs
> node install.js

Download already available at /tmp/phantomjs/phantomjs-1.9.8-linux-i686.tar.bz2
Extracting tar contents (via spawned process)
Removing /home/olivier/Projects/hwwa/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-1.9.8-linux-i686.tar.bz2-extract-1423694714242/phantomjs-1.9.8-linux-i686 -> /home/olivier/Projects/hwwa/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/olivier/Projects/hwwa/node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/phantom/bin/phantomjs
npm WARN optional dep failed, continuing fsevents@0.2.1
npm WARN engine coffee-script-redux@2.0.0-beta4: wanted: {"node":"0.6.x || 0.8.x"} (current: {"node":"0.12.0","npm":"2.5.0"})
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git Cloning into bare repository '/home/olivier/.npm/_git-remotes/git-github-com-michaelficarra-cscodegen-git-c4b567f3'...
npm ERR! git clone git://github.com/michaelficarra/cscodegen.git fatal: read error: Connection reset by peer
npm WARN optional dep failed, continuing cscodegen@git://github.com/michaelficarra/cscodegen.git#73fd7202ac086c26f18c9d56f025b18b3c6f5383
 
> ws@0.4.32 install /home/olivier/Projects/hwwa/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory `/home/olivier/Projects/hwwa/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node: Finished
  COPY Release/bufferutil.node
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  SOLINK_MODULE(target) Release/obj.target/validation.node: Finished
  COPY Release/validation.node
make: Leaving directory `/home/olivier/Projects/hwwa/node_modules/karma/node_modules/socket.io/node_modules/socket.io-client/node_modules/ws/build'
grunt-rev@0.1.0 node_modules/grunt-rev

karma-jasmine@0.1.5 node_modules/karma-jasmine

grunt-contrib-concat@0.3.0 node_modules/grunt-contrib-concat

jshint-stylish@0.1.5 node_modules/jshint-stylish
├── text-table@0.2.0
└── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)

grunt-contrib-copy@0.4.1 node_modules/grunt-contrib-copy

grunt-concurrent@0.4.3 node_modules/grunt-concurrent
├── lpad@0.1.0
└── async@0.2.10

time-grunt@0.2.10 node_modules/time-grunt
├── date-time@0.1.1
├── chalk@0.4.0 (has-color@0.1.7, ansi-styles@1.0.0, strip-ansi@0.1.1)
├── text-table@0.2.0
└── hooker@0.2.3

grunt-contrib-clean@0.5.0 node_modules/grunt-contrib-clean
└── rimraf@2.2.8

grunt-contrib-htmlmin@0.1.3 node_modules/grunt-contrib-htmlmin
├── html-minifier@0.5.6
└── grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)

grunt-newer@0.6.1 node_modules/grunt-newer
├── async@0.2.9
└── rimraf@2.2.4 (graceful-fs@2.0.3)

grunt-contrib-cssmin@0.7.0 node_modules/grunt-contrib-cssmin
├── grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)
└── clean-css@2.0.8 (commander@2.0.0)

grunt-karma@0.6.2 node_modules/grunt-karma
└── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)

grunt-usemin@2.0.2 node_modules/grunt-usemin
├── debug@0.7.4
└── lodash@1.0.1

grunt-autoprefixer@0.5.0 node_modules/grunt-autoprefixer
├── diff@1.0.8
└── autoprefixer@0.8.20131213 (css-parse@1.6.0, css-stringify@1.4.1)

grunt-contrib-connect@0.5.0 node_modules/grunt-contrib-connect
├── connect-livereload@0.2.0
├── open@0.0.4
└── connect@2.7.11 (fresh@0.1.0, cookie-signature@1.0.1, pause@0.0.1, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.0.5, debug@2.1.1, send@0.1.1, formidable@1.0.14)

grunt-ngmin@0.0.3 node_modules/grunt-ngmin
└── ngmin@0.4.1 (astral@0.1.0, clone@0.1.19, commander@1.1.1, astral-angular-annotate@0.0.2, escodegen@0.0.28, esprima@1.0.4)

load-grunt-tasks@0.2.1 node_modules/load-grunt-tasks
├── globule@0.1.0 (minimatch@0.2.14, glob@3.1.21, lodash@1.0.1)
└── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)

grunt-contrib-uglify@0.2.7 node_modules/grunt-contrib-uglify
├── grunt-lib-contrib@0.6.1 (zlib-browserify@0.0.1)
└── uglify-js@2.4.16 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7, source-map@0.1.34)

grunt-contrib-watch@0.5.3 node_modules/grunt-contrib-watch
├── tiny-lr@0.0.4 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5.6)
└── gaze@0.4.3 (globule@0.1.0)

karma-phantomjs-launcher@0.1.4 node_modules/karma-phantomjs-launcher
└── phantomjs@1.9.15 (which@1.0.8, progress@1.1.8, kew@0.4.0, request-progress@0.3.1, fs-extra@0.16.3, adm-zip@0.4.4, npmconf@2.0.9, request@2.42.0)

grunt@0.4.5 node_modules/grunt
├── which@1.0.8
├── dateformat@1.0.2-1.2.3
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── rimraf@2.2.8
├── colors@0.6.2
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── hooker@0.2.3
├── nopt@1.0.10 (abbrev@1.0.5)
├── exit@0.1.2
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)
├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
└── js-yaml@2.0.5 (argparse@0.1.16, esprima@1.0.4)

grunt-bower-install@0.7.0 node_modules/grunt-bower-install
└── wiredep@0.4.2 (chalk@0.1.1, lodash@1.3.1)

grunt-contrib-jshint@0.7.2 node_modules/grunt-contrib-jshint
└── jshint@2.3.0 (console-browserify@0.1.6, underscore@1.4.4, minimatch@0.4.0, shelljs@0.1.4, cli@0.4.5)

grunt-google-cdn@0.4.3 node_modules/grunt-google-cdn
├── chalk@0.5.1 (escape-string-regexp@1.0.2, ansi-styles@1.1.0, supports-color@0.2.0, has-ansi@0.1.0, strip-ansi@0.3.0)
├── google-cdn@0.7.0 (regexp-quote@0.0.0, google-cdn-data@0.1.17, async@0.9.0, debug@1.0.4, semver@2.3.2, cdnjs-cdn-data@0.1.1)
└── bower@1.3.12 (is-root@1.0.0, junk@1.0.0, stringify-object@1.0.0, which@1.0.8, abbrev@1.0.5, chmodr@0.1.0, osenv@0.1.0, archy@0.0.2, opn@1.0.1, rimraf@2.2.8, lru-cache@2.5.0, bower-logger@0.2.2, bower-endpoint-parser@0.2.2, graceful-fs@3.0.5, lockfile@1.0.0, nopt@3.0.1, retry@0.6.0, tmp@0.0.23, q@1.0.1, request-progress@0.3.0, chalk@0.5.0, shell-quote@1.4.2, bower-json@0.4.0, semver@2.3.2, fstream@1.0.4, promptly@0.2.0, p-throttler@0.1.0, mkdirp@0.5.0, bower-config@0.5.2, fstream-ignore@1.0.2, mout@0.9.1, tar-fs@0.5.2, decompress-zip@0.0.8, cardinal@0.4.0, inquirer@0.7.1, glob@4.0.6, request@2.42.0, bower-registry-client@0.2.3, insight@0.4.3, update-notifier@0.2.0, handlebars@2.0.0)

karma-coverage@0.1.5 node_modules/karma-coverage
├── dateformat@1.0.11 (get-stdin@4.0.1, meow@3.0.0)
├── istanbul@0.1.46 (which@1.0.8, abbrev@1.0.5, nopt@2.1.2, wordwrap@0.0.2, async@0.2.10, mkdirp@0.3.5, resolve@0.5.1, fileset@0.1.5, esprima@1.0.4, escodegen@0.0.23, handlebars@1.0.12)
└── ibrik@1.0.1 (which@1.0.8, estraverse@1.9.1, mkdirp@0.5.0, optimist@0.6.1, escodegen@1.6.1, coffee-script-redux@2.0.0-beta4)

karma-firefox-launcher@0.1.4 node_modules/karma-firefox-launcher

karma-script-launcher@0.1.0 node_modules/karma-script-launcher

karma-chrome-launcher@0.1.7 node_modules/karma-chrome-launcher

karma-html2js-preprocessor@0.1.0 node_modules/karma-html2js-preprocessor

requirejs@2.1.16 node_modules/requirejs

karma-requirejs@0.2.2 node_modules/karma-requirejs

karma-coffee-preprocessor@0.1.3 node_modules/karma-coffee-preprocessor
└── coffee-script@1.7.1 (mkdirp@0.3.5)

karma@0.10.10 node_modules/karma
├── di@0.0.1
├── rimraf@2.1.4
├── colors@0.6.0-1
├── graceful-fs@1.2.3
├── mime@1.2.11
├── q@0.9.7
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── glob@3.1.21 (inherits@1.0.0)
├── optimist@0.3.7 (wordwrap@0.0.2)
├── chokidar@0.8.4 (recursive-readdir@0.0.2)
├── coffee-script@1.6.3
├── lodash@1.1.1
├── http-proxy@0.10.4 (colors@0.6.2, pkginfo@0.3.0, optimist@0.6.1, utile@0.2.1)
├── connect@2.8.8 (uid2@0.0.2, methods@0.0.1, cookie-signature@1.0.1, pause@0.0.1, fresh@0.2.0, qs@0.6.5, bytes@0.2.0, buffer-crc32@0.2.1, cookie@0.1.0, formidable@1.0.14, send@0.1.4, debug@2.1.1)
├── useragent@2.0.10 (lru-cache@2.2.4)
├── log4js@0.6.22 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
└── socket.io@0.9.17 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-client@0.9.16)
</pre>
